### ISSUE TITLE
Test implementations

### ISSUE THREAD

**Issue by biancamacias** [GoogleCloudPlatform/cloud-spanner-samples#10]
## Issue
Currently, there are no unit tests for any implementation. Adding testing by mocking the emulator and/or grpc_cli will help ensure that the code runs as expected

## Expected Behavior
when running the unit tests, switching the flag should result in using the correct implementation (either java client or JDBC)

## Next Steps

- [ ] look into Mockito to mock grpc or emulator
- [ ] create unit tests to verify expected behavior
- [ ] this issue will become more detailed as the test files are pushed

**Comment by ngcgarcia** [comment]
Resolved with #21, #28, and #45.
