### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by biancamacias** [GoogleCloudPlatform/cloud-spanner-samples#14]
## Issue
with the new flag that switches between implementations and new command line instructions, we need to update the `README`.

- [ ] add documentation about how to switch the flag
- [ ] update commands about how to run the emulator
- [ ] specify separate terminal windows to run the emulator, grpc service, and to call the RPCs
- [ ] update commands about running the server

**Comment by c24t** [comment]
From #39 

> Because of the repo restructuring in #36, commands on the README might not work (such as when getting the schema.sdl, now must specify coming from `server/src/main/java/com/google/finapp/schemda.sdl`)

> This also applies to the command to bring up the grpc service. It should now be ` java -jar target/server-1.0-SNAPSHOT-jar-with-dependencies.jar --spanner_project_id=test-project --spanner_instance_id=test-instance --spanner_database_id=test-database`
