### ISSUE TITLE
Investigate methods for running the emulator for tests

### ISSUE THREAD

**Issue by ngcgarcia** [GoogleCloudPlatform/cloud-spanner-samples#31]
## Issue

As of now, our test suite requires that the user sets up and runs the emulator in a separate terminal. Ideally, we would have some command or some other method to automatically do that for the user so that they do not have to configure and run the emulator for themselves. 

Possible methods (list in progress):
- [AntRun Plugin](https://maven.apache.org/plugins/maven-antrun-plugin/)

## Next Steps 

- [ ] Investigate methods
- [ ] Implement a strategy to lower user effort for running tests

**Comment by haseebajmal** [comment]
Consider looking into github workflows. Example: https://github.com/googleapis/java-spanner/pull/310/

**Comment by haseebajmal** [comment]
https://github.com/GoogleCloudPlatform/cloud-spanner-samples/tree/it branch has a fully working solution (with gradle).

**Comment by voulg** [comment]
Added github action for continuous integration with emulator on https://github.com/GoogleCloudPlatform/cloud-spanner-samples/pull/61
