### ISSUE TITLE
Consider creating a custom exception for invalid inputs

### ISSUE THREAD

**Issue by ngcgarcia** [GoogleCloudPlatform/cloud-spanner-samples#34]
## Issues

Currently, we throw `IllegalArgumentException` (an unchecked exception) for certain invalid inputs (i.e. negative amounts in `moveAccountBalance`). We catch these exceptions in `FinAppService` in order to provide useful feedback to users, but we could also be catching exceptions unrelated to the specific ones we're looking for (the ones we throw). We also expect these exceptions in our tests (namely, `moveAccountBalance`, which is being added soon) even though they are not in the signature. 

A possible fix for this is creating a custom checked exception. This would mean that we could include it in our method signatures to then test and that we could specifically catch this exception.

**Comment by voulg** [comment]
Fixed by https://github.com/GoogleCloudPlatform/cloud-spanner-samples/pull/63
