### ISSUE TITLE
README now out of date

### ISSUE THREAD

**Issue by biancamacias** [GoogleCloudPlatform/cloud-spanner-samples#39]
## Issue
Because of the repo restructuring in #36, commands on the README might not work (such as when getting the schema.sdl, now must specify coming from `server/src/main/java/com/google/finapp/schemda.sdl`)

This also applies to the command to bring up the grpc service. It should now be ` java -jar target/server-1.0-SNAPSHOT-jar-with-dependencies.jar --spanner_project_id=test-project --spanner_instance_id=test-instance --spanner_database_id=test-database`

**Comment by c24t** [comment]
Closing in favor of #14.
