### ISSUE TITLE
Default timestamps for GetRecentTransactionsForAccount

### ISSUE THREAD

**Issue by biancamacias** [GoogleCloudPlatform/cloud-spanner-samples#46]
## Issue

Currently, the rpc GetRecentTransactionsForAccount does not have default timestamps. If only the `begin_timestamp` attribute is given, the default `end_timestamp` could be `Timestamp.MAX_VALUE` and vice versa.

**Comment by c24t** [comment]
See https://github.com/GoogleCloudPlatform/cloud-spanner-samples/pull/37#discussion_r695250963.
