### ISSUE TITLE
Test suite cleanup FinAppIT

### ISSUE THREAD

**Issue by biancamacias** [GoogleCloudPlatform/cloud-spanner-samples#48]
## Issue
Currently, `FinAppIT` reuses a `databaseClient.write` method over and over again. The types and statuses are also unspecified, but this might not be able to be resolved until #47 is addressed. 

## Next Steps

- [ ] move method to a private method that can create accounts for the tests easily.
- [ ] make the account types and statuses not unspecified

**Comment by voulg** [comment]
Private helper done in https://github.com/GoogleCloudPlatform/cloud-spanner-samples/pull/59, the unspecified statuses will be addressed as part of #47
