### ISSUE TITLE
Pagination for GetRecentTransactionsForAccount rpc

### ISSUE THREAD

**Issue by biancamacias** [GoogleCloudPlatform/cloud-spanner-samples#49]
## Issue
Currently, the rpc needs 2 timestamps (begin and end) to query results.

## Next Steps
Come up with a way to query results in a `LIMIT BY` way. Beware that Spanner can perform poorly executing certain SQL statements.

**Comment by c24t** [comment]
See https://github.com/GoogleCloudPlatform/cloud-spanner-samples/pull/37#issuecomment-905018316.
